config:
  image_grid_width_sm: 640
  image_grid_width_md: 1080
  image_grid_width_lg: 1800
  image_width_sm: 1080
  image_width_md: 1800
  image_width_lg: 2400
  font_stack_system: >-
    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
    Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
metadata:
  site_url: 'https://pipebenitez.com'
  site_title: Pipe Benitez
  site_description: >
    Taking photos in New York City. Mostly people, sometimes places. Also making
    things with <a href="https://www.cristhiantilleria.com">design and code</a>.
    It’s not always connected, but it feels part of the same thread.
  site_email: hello@pipebenitez.com
  site_social_url: 'https://www.instagram.com/pipephoto_/'
  site_icon_svg: /assets/uploads/favicon.svg
  site_icon_png: ''
  site_ga4_id: ''
  contact_description: >
    I'd love to hear about your project. Whether it's a portrait session, event coverage,
    or something completely different, let's chat about bringing your vision to life.
  seo:
    site_title: Pipe Benitez
    site_description: >-
      NYC-based photographer exploring the intersection of photography, design,
      and engineering. Creating visual narratives.
    no_index: false
theme:
  theme_layout:
    space_scale: 100
  theme_colors:
    background: '#ffffff'
    text: '#101010'
    link: '#101010'
    background_dark: '#101010'
    text_dark: '#E1E1E1'
    link_dark: '#FFFFFF'
  theme_typography:
    font: Space Grotesk
    font_weight: 400
    font_scale: 100
    line_height_scale: 100
  theme_features:
    enable_dark_mode: true
    item_output_limit: 48
    transition_duration: 300
    show_project_year: true
    show_project_grid_titles: true
images:
  avif:
    enabled: false
  webp:
    enabled: true
    quality: 75
  jpeg:
    enabled: true
    quality: 75
i18n:
  site_language: en
  site_social_title: Instagram
